// TypeScript mirrors of the Rust v3 surface (spec §四 / §五 / §十一).
//
// Kept intentionally small — `lib/tauri.ts` is the single source of
// truth for IPC; this file only types what crosses that boundary.
//
// Types re-exported from `@corivo/shared-types` are auto-generated by
// `ts-rs` from Rust structs; everything else below is still hand-written
// and migrates one struct at a time as Rust gets `#[derive(TS)]`.

export type { TauriError } from "@corivo/shared-types"

// --------------------------------------------------------------------------
// Frames (spec §五)
// --------------------------------------------------------------------------

export type ExtractionStrategy = "ax" | "ocr" | "ax+ocr" | "skipped";

export interface Frame {
  id: string;
  captured_at: string;
  device_id: string;
  capture_session_id: string;

  app_bundle_id: string | null;
  app_name: string | null;
  window_title: string | null;
  url: string | null;

  screenshot_path: string | null;
  screenshot_hash: string | null;
  screenshot_size_bytes: number | null;

  ax_text: string | null;
  ocr_text: string | null;
  extraction_strategy: ExtractionStrategy;
  extraction_duration_ms: number | null;
  fallback_reason: string | null;

  content_hash: string | null;
  derived_from_frame_id: string | null;
  still_present_until: string | null;

  exclusion_match: string | null;

  created_at: string;
}

export interface ListFramesArgs {
  from?: string | null;
  to?: string | null;
  app_bundle_id?: string | null;
  limit?: number | null;
  offset?: number | null;
}

// --------------------------------------------------------------------------
// Capture pipeline
// --------------------------------------------------------------------------

export type CapturePhase = "running" | "stopped";

export interface CaptureStatus {
  phase: CapturePhase;
  current_session_id: string | null;
  /** RFC3339 UTC instant when the menubar pause expires. `null` means
   *  capture is not paused. Frontend formats the local-time delta for
   *  the sidebar status row. */
  paused_until: string | null;
}

// --------------------------------------------------------------------------
// Config (mirrors Rust `Config`; we only type what the UI actually reads)
// --------------------------------------------------------------------------

export type Language = "zh" | "en";

/** Visual theme preference. Mirrors Rust `ThemePreference`.
 *  `system` follows macOS appearance via `prefers-color-scheme`. */
export type ThemePreference = "light" | "dark" | "system";

export interface AppConfig {
  minimize_to_tray: boolean;
  /** Language Corivo's interface is rendered in. Mirrors
   *  `Config.app.ui_language` on the Rust side. */
  ui_language: Language;
  /** Language the AI replies in inside `/ask` and Quick Ask. Mirrors
   *  `Config.app.response_language` on the Rust side. Independent from
   *  `ui_language` so a Chinese-UI user can still get English answers
   *  (and vice versa). */
  response_language: Language;
  start_capture_on_launch: boolean;
  onboarding_completed: boolean;
  onboarding_version: number;
  onboarding_step: string | null;
  /** Visual theme. `useThemeSync` hook applies `[data-theme]` on
   *  `<html>` based on this. Default `system`. */
  theme: ThemePreference;
  /** Onboarding handoff flag — `false` until the user completes their
   *  very first Quick Ask turn during the Try-It step. Quick Ask reads
   *  this to decide whether to show the 3 suggestion chips and to fire
   *  the `onboarding:first-quick-ask` event so the onboarding window
   *  can dismiss itself. Once flipped to `true` it stays true for the
   *  life of the install — the chips never come back. */
  first_quick_ask_done: boolean;
  /** RFC3339 UTC instant the menubar pause expires. `null` when not
   *  paused. The backend's tray menu owns this field; the frontend
   *  reads it via `CaptureStatus` rather than `Config` for live updates. */
  capture_paused_until: string | null;
  /** Hidden "developer mode" toggle, unlocked by triple-clicking the
   *  settings dialog title. When `true`, the settings sidebar surfaces a
   *  "Developer" section with WebView DevTools + on-device debugging
   *  shortcuts. Disable from inside the section itself. Default false. */
  developer_mode: boolean;
}

export interface CaptureConfig {
  interval_secs: number;
  batch_size: number;
  max_storage_gb: number;
  jpeg_quality: number;
  broadcast_capacity: number;
}

export interface PromptDebugConfig {
  summary_override: string | null;
  push_judgment_override: string | null;
  suggest_override: string | null;
  score_override: string | null;
}

export interface SoulConfig {
  preset: "gentle" | "accomplice" | "old_friend" | "coach" | "custom";
  custom_text: string | null;
}

export interface UserModelConfig {
  batcher: { min_batch_size: number; flush_interval_ms: number };
  retrieval: {
    w_confidence: number;
    w_decay: number;
    k_decay_days: number;
    limit_multiplier: number;
  };
  pipeline: { similar_pool_size: number; min_draft_count: number };
}

export interface ReconcileConfig {
  enabled: boolean;
  merge_enabled: boolean;
  stream_enabled: boolean;
  interval_hours: number;
  min_workcontexts_per_project_for_stream: number;
}

export interface FocusSessionConfig {
  enabled: boolean;
  gap_minutes: number;
  idle_close_multiplier: number;
  max_session_hours: number;
}

export interface Config {
  capture: CaptureConfig;
  app: AppConfig;
  prompt_debug: PromptDebugConfig;
  user_model: UserModelConfig;
  soul: SoulConfig;
  reconcile: ReconcileConfig;
  focus_session: FocusSessionConfig;
  exec_agent: ExecAgentConfig;
  corivo_session: CorivoSessionConfig;
}

export interface CorivoSessionConfig {
  /** Closed-beta bearer token pair persisted in `config.json`
   *  alongside everything else. `null` ↔ "not logged in". */
  session_token: string | null;
}

// --------------------------------------------------------------------------
// Exec-agent auth (spec §7.4).
// --------------------------------------------------------------------------

export type ExecAgentAuthMode = "corivo_proxy" | "byok" | "chatgpt";

/** Mirror of Rust `ChatgptAuthConfig` — persisted ChatGPT subscription
 *  creds. The UI only reads `account_id` to decide "signed-in" + the
 *  email / plan for the status pane; tokens themselves never leave the
 *  Rust side. */
export interface ChatgptAuthConfig {
  access_token: string | null;
  refresh_token: string | null;
  id_token: string | null;
  account_id: string | null;
  plan_type: string | null;
  email: string | null;
  /** RFC3339 absolute expiry. The Rust runtime refreshes the token
   *  ~5 min before this hits. */
  expires_at: string | null;
}

/** Mirror of Rust `ChatgptAuthStatus` — the stripped-down view the
 *  Settings status pane consumes. Token material never crosses this
 *  boundary. */
export interface ChatgptAuthStatusView {
  signedIn: boolean;
  email: string | null;
  planType: string | null;
  expiresAt: string | null;
  accountId: string | null;
}

// Closed-beta auth surface + skill listing — ts-rs generated, single
// source of truth.
export type {
  ApiShape,
  AuthStatus,
  AvailableSkill,
  AvailableSkillKind,
  AvailableSkillSource,
  ThinkingLevel,
} from "@corivo/shared-types";

import type { ApiShape, ThinkingLevel } from "@corivo/shared-types";

export interface SkillShareConfig {
  enabled: string[];
  initialized: boolean;
}

export interface ExecAgentConfig {
  auth_mode: ExecAgentAuthMode;
  /** CorivoProxy mode: id of the model the user picked from the
   *  cached `/v1/models` list (spec §7.2). Sidecar resolves api_shape
   *  + compaction partner via the cache. `null` → no model selected
   *  yet (the picker UI nudges the user to choose). */
  selected_model_id: string | null;
  /** Byok mode: provider protocol shape pi-ai uses inside the sidecar. */
  byok_api_shape: ApiShape | null;
  /** Byok mode: optional override for the provider base URL. `null`
   *  falls back to the SDK default. */
  byok_base_url: string | null;
  /** Byok mode: user-supplied API key. */
  byok_key: string | null;
  /** Byok mode: user-supplied model id (e.g. `gpt-4o`). Validated by
   *  the sidecar against `/v1/models` on startup. */
  byok_model: string | null;
  /** Reasoning budget the sidecar forwards to pi-ai on the main turn. */
  thinking_level: ThinkingLevel;
  skill_share: SkillShareConfig;
  /** ChatGPT subscription tokens. Empty/null when the user is not
   *  signed in with ChatGPT. The Settings UI calls
   *  `chatgpt_auth_login` / `_logout` to mutate this — never edited
   *  by direct `setConfig`. */
  chatgpt: ChatgptAuthConfig;
}

// --------------------------------------------------------------------------
// Onboarding + settings
// --------------------------------------------------------------------------

export interface OnboardingState {
  completed: boolean;
  version: number;
  current_version: number;
  needs_onboarding: boolean;
  step: string | null;
}

export interface SystemInfo {
  os: string;
  arch: string;
  os_version: string;
  app_version: string;
  tauri_version: string;
}

export interface DataPaths {
  app_data_dir: string;
  config_path: string;
  captures_dir: string;
}

export interface StorageStats {
  captures_dir: string;
  total_size_bytes: number;
  session_count: number;
  screenshot_count: number;
}

// --------------------------------------------------------------------------
// Chat / `/ask` (spec §五 + §八 + §十一)
// --------------------------------------------------------------------------

// `ChatRole`, `ContentBlock`, `MessageStatus`, `Usage` are ts-rs generated
// — the Rust definitions in `domain::chat` are the single source of truth.
export type {
  ChatRole,
  ContentBlock,
  MessageStatus,
  Usage,
} from "@corivo/shared-types";

import type {
  ChatRole,
  ContentBlock,
  MessageStatus,
  Usage,
} from "@corivo/shared-types";

export interface ChatThread {
  id: string;
  title: string | null;
  /** Spec §8.2: model the thread was created against. Sidecar reads
   *  this instead of the live Settings selection so a mid-conversation
   *  Settings switch doesn't derail the active turn. The thread list
   *  UI surfaces the corresponding `display_name` as a small badge. */
  bound_model_id: string;
  bound_api_shape: ApiShape;
  /** v1300 sidebar lifecycle. ISO timestamp when the user pinned the
   *  thread; `null` when not pinned. The sidebar groups pinned threads
   *  under a "置顶" section above "最近". */
  pinned_at: string | null;
  /** v1300 sidebar lifecycle. ISO timestamp when the user archived
   *  the thread; `null` when not archived. Archived threads are
   *  hidden from "最近" and surfaced only when the "归档(N)"
   *  disclosure expands. Archive dominates pin in the UI. */
  archived_at: string | null;
  created_at: string;
  updated_at: string;
}

/** v1200 chat_messages row. `content_blocks` is the canonical rich
 *  representation — text / thinking / tool_use / tool_result /
 *  focus_context / frame_citation; `content_text` is the plain-text
 *  rollup (concat of all text + thinking) for FTS / sidebar preview.
 *
 *  `status` distinguishes `complete` (terminal, normal turn) /
 *  `streaming` (assistant placeholder still being filled — filtered
 *  out of by-thread reads) / `error` / `cancelled`. */
export interface ChatMessage {
  id: string;
  thread_id: string;
  role: ChatRole;
  content_blocks: ContentBlock[];
  content_text: string;
  cited_frame_ids: string[] | null;
  status: MessageStatus;
  error_message: string | null;
  finish_reason: string | null;
  usage: Usage | null;
  /** Model directory alias that actually drove this assistant turn —
   *  set by the backend right after runtime resolution. `null` for
   *  user rows, for BYOK assistant rows (no alias to track), and for
   *  legacy assistant rows from before v1301. UI should treat `null`
   *  as "unknown model" rather than a bug. */
  model_used: string | null;
  created_at: string;
  updated_at: string | null;
}

/** JSON-Lines stream event the recall orchestrator pushes over the
 *  Tauri Channel (spec §八 — Phase 3 uses a custom shape; Phase 3.5
 *  may swap to Vercel AI SDK Data Stream Protocol). */
export type ChatStreamEvent =
  | { type: "text-delta"; text: string }
  | {
      type: "tool-call";
      id: string;
      name: string;
      args: Record<string, unknown>;
    }
  | { type: "tool-result"; id: string; result: unknown }
  | { type: "cited-frames"; frame_ids: string[] }
  | {
      /** Transient progress hint that doesn't change message content.
       *  Currently emitted as `kind: "api-retry"` while the SDK retries
       *  failed HTTP requests so the UI doesn't sit silent for the full
       *  backoff. Cleared when actual content (text/tool/finish/error)
       *  arrives. */
      type: "status";
      kind: string;
      detail: string | null;
    }
  | {
      type: "finish";
      // `cancelled` is emitted by the corivo-agent runner when
      // `exec_agent_cancel` fires the per-thread cancel signal. The UI
      // treats it as a neutral end-of-stream (no error chrome) — the
      // partial assistant content is kept and persisted as-is.
      reason: "end-turn" | "truncated" | "error" | "cancelled";
    }
  | { type: "error"; message: string };

// --------------------------------------------------------------------------
// Quick Ask (spec §六 + §八 + §十一)
// --------------------------------------------------------------------------

export interface FocusContext {
  frame_id: string;
  captured_at: string;
  app_bundle_id: string | null;
  app_name: string | null;
  window_title: string | null;
  url: string | null;
  adapter_name: string | null;
  /** Adapter-specific structured payload — opaque to the UI except a
   *  couple of well-known keys (`url`, `path`, `cwd`) the FocusCard
   *  may surface as a subtitle. */
  adapter_payload: Record<string, unknown> | null;
  /** First-pass extraction (AX or OCR text). The window shows the
   *  first ~200 chars; the full body can be fetched via
   *  `get_frame_text(frame_id)` from the recall toolset. */
  primary_text: string;
  /** User's currently-highlighted text on the focused window,
   *  captured via the AX `AXSelectedTextMarkerRange` post-step.
   *  `null` when there's no active selection or the host app
   *  doesn't expose marker ranges. Quick Ask passes this to the
   *  agent as a separate "用户高亮选区" block alongside `primary_text`. */
  selection: string | null;
  excluded: boolean;
  empty: boolean;
}

/** Subset of FocusContext available right after probe + screenshot.
 *  Sent in the `quick-ask:opened` event when the AX walk is still
 *  pending — FocusCard renders the title row from this and the full
 *  FocusContext arrives later via `quick-ask:focus-ready`. */
export interface QuickAskSkeleton {
  captured_at: string;
  app_bundle_id: string | null;
  app_name: string | null;
  window_title: string | null;
  url: string | null;
}

/** Discriminated payload of the `quick-ask:opened` event. The
 *  `pending` variant is emitted on the fast path (window shown
 *  immediately, AX walk in flight); the `ready` variant is emitted
 *  when the focus app is on the exclusion list and there's no
 *  extraction work left to do.
 *
 *  Note: no `thread` field. Quick Ask uses type-to-create — the
 *  `chat_threads` row materializes in the frontend on the first send
 *  via `useChatStream::createThreadIfMissing`, same as `/ask`. */
export type QuickAskOpenedPayload =
  | {
      kind: "pending";
      skeleton: QuickAskSkeleton;
    }
  | {
      kind: "ready";
      focus: FocusContext;
    };

/** Quick Ask hotkey shape. The backend reports the platform-specific
 * bare-modifier gesture so the UI can render Option on macOS and Alt
 * on Windows without guessing. */
export type HotkeyBinding = "double_tap_option" | "double_tap_alt";

export interface HotkeyStatus {
  binding: HotkeyBinding;
  installed: boolean;
  error: string | null;
}
